import networkx as nx
import matplotlib.pyplot as plt

g = nx.DiGraph()
g.add_nodes_from(["a","b","c","g","d","e","f","h","i","j","k"])
g.add_edge("a","b")
g.add_edge("b","g")
g.add_edge("a","c")
g.add_edge("c","g")
g.add_edge("a","g")
g.add_edge("b","d")
g.add_edge("d","e")
g.add_edge("e","g")
g.add_edge("c","f")
g.add_edge("f","h")
g.add_edge("h","g")
g.add_edge("e","i")
g.add_edge("h","j")
g.add_edge("i","g")
g.add_edge("i","k")
g.add_edge("j","g")
g.add_edge("j","i")
g.add_edge("k","g")
g.add_edge("k","g")

plt.figure().suptitle("Planar Layout")
nx.draw_planar(g,with_labels=True)
plt.figure().suptitle("Circular Layout")
nx.draw_circular(g,with_labels=True)
plt.figure().suptitle("Kamada-Kawai force-directed Layout")
nx.draw_kamada_kawai(g,with_labels=True)
plt.show()
